# -*- coding: utf-8 -*-
"""final proyek teknir.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ikN1HGU9QzmDMw80yQS4F9-Wu-w6smEL

# **Install packages**
"""

install.packages("caret", repos = "http://cran.us.r-project.org")
install.packages("randomForest", repos = "http://cran.us.r-project.org")
install.packages("ggplot2", repos = "http://cran.us.r-project.org")
install.packages("dplyr", repos = "http://cran.us.r-project.org")

"""# **Import Library**"""

library(caret)
library(randomForest)
library(dplyr)
library(ggplot2)

"""# **Unduh dan Muat Data**"""

# Unduh data
download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", destfile = "pml-training.csv")
download.file("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv", destfile = "pml-testing.csv")

# Baca file CSV
training_raw <- read.csv("/content/pml-training.csv", na.strings=c("NA", "", "#DIV/0!"))
testing_raw <- read.csv("/content/pml-testing.csv", na.strings=c("NA", "", "#DIV/0!"))

"""# **Pembersihan Data**"""

# Hapus kolom dengan banyak NA
training <- training_raw[, colSums(is.na(training_raw)) == 0]

# Hapus kolom non-predictor (user info, timestamps, dll)
training <- training[, -(1:7)]

# Buat partisi training dan validasi
set.seed(123)
inTrain <- createDataPartition(training$classe, p=0.7, list=FALSE)
trainData <- training[inTrain, ]
validData <- training[-inTrain, ]

"""# **Pembuatan Model Random Forest**"""

set.seed(123)
model_rf <- train(classe ~ ., data=trainData, method="rf", trControl=trainControl(method="cv", number=5), ntree=100)

""" **Prediksi**"""

# Samakan kolom dengan training
test <- testing_raw[, names(testing_raw) %in% names(trainData)]

# Prediksi
pred_final <- predict(model_rf, newdata=test)

# Tampilkan hasil
pred_final

"""# (opsional)"""

write.table(pred_final, file="hasil_prediksi.txt", row.names=FALSE, quote=FALSE)

"""memuat ulang data testing"""

# Load library
library(readr)

# Baca file testing dari URL
testing <- read_csv("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv", na = c("NA", "", "#DIV/0!"))

# Lihat struktur awal
str(testing)

answers <- predict(model_rf, newdata = testing)
print(answers)

training <- read.csv("https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv", na.strings=c("NA","#DIV/0!",""))
head(training)

str(training)

unique(training$user_name)

table(training$user_name)